spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/learning-db}
    username: ${DB_USERNAME:MarkedOne}
    password: ${DB_PASSWORD:GuysIcaughtAnOlive}
    driver-class-name: org.postgresql.Driver

hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  ddl-auto: update

security:
  secret: SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
